-- import:
--local c = require("TTS-YGO-sealed-draft/dev/draft-table/DraftTableCreator")

local cardGridJson = require("TTS-YGO-sealed-draft/dev/room-creation/draft-table/CardGrid")
local util = require("TTS-YGO-sealed-draft/dev/room-creation/draft-table/Util")

local module = {}

local v = Vector

local tableScale = v(3.50, 1.00, 2.00)
local plateScale = v(0.85, 0.20, 0.47)
local hiddenZoneScale = v(40, 15, 60)
local cardGridScale = v(9, 2, 9)

function createCardGrid(zone)
    local size = zone.getScale()
    local pos = util.relativeLocalToWorldPosition2D(zone, size, -1, -1)
    local rotation = zone.getRotation()

    spawnParams = {
        json              = cardGridJson,
        position          = pos,
        rotation          = rotation,
        scale             = cardGridScale,
        sound             = false,
        snap_to_grid      = true,
        callback_function = function(grid)
            local f = function()
                local size = v(grid.getBoundsNormalized().size)
                util.moveForwards(grid, size.z/2)
                util.moveRight(grid, size.x/2)
                grid.setLock(true)
            end
            Wait.time(f, 2)
        end
    }
    spawnObjectJSON(spawnParams)
end

function createCardGrids()
    local firstLeftPosition = pos + v(-23, 1, 102)
    local firstRightPosition = pos + v(23, 1, 102)
    local leftRotation = rotation + v(0, 180, 0)
    local rightRoration = rotation

    local p = firstLeftPosition
    for i=1,4 do
        createCardGrid(p, leftRotation)
        p = p + v(0, 0, -50)
    end

    p = firstRightPosition
    for i=1,4 do
        createCardGrid(p, rightRoration)
        p = p + v(0, 0, -50)
    end
end

function createHiddenZone(pos, rotation, left, color)
    spawnParams = {
        type = "FogOfWarTrigger",
        position = pos,
        rotation = rotation,
        scale = hiddenZoneScale,
        sound = false,
        snap_to_grid = false,
        callback_function = function(zone)
            zone.setValue(color)
            util.moveBackwards(zone, zone.getScale().z/2)
            if left then util.moveLeft(zone, zone.getScale().x/2) else util.moveRight(zone, zone.getScale().x/2) end
            util.moveUp(zone, zone.getScale().y/2)

            Wait.frames(||createCardGrid(zone), 2)
         end
    }
    spawnObject(spawnParams)
end

function createHiddenZones(plate)
    local color = {"Green", "Teal", "Blue", "Purple", "White", "Red", "Orange", "Yellow"}
    local x2d = 1.0
    local y2d = 1.0
    local rotation = plate.getRotation()
    local size = plate.getBoundsNormalized().size

    for i=1,4 do
        local pos = util.relativeLocalToWorldPosition2D(plate, size, x2d, y2d)
        createHiddenZone(pos, rotation, true, color[i])
        x2d = x2d - 0.42
    end

    x2d = 1.0
    y2d = -1.0
    rotation = rotation + v(0, 180, 0)

    for i=5,8 do
        local pos = util.relativeLocalToWorldPosition2D(plate, size, x2d, y2d)
        createHiddenZone(pos, rotation, false, color[i])
        x2d = x2d - 0.42
    end

end

function createText(plate)
    local parentSize = plate.getBoundsNormalized().size
    local pos = util.relativeLocalToWorldPosition2D(plate, parentSize, -0.85, -0.4)

    spawnParams = {
        type = "3DText",
        position = pos + v(0, 2, 0),
        rotation = plate.getRotation() + v(90,0,-90),
        sound = false,
        snap_to_grid = false,
        callback_function = function(text)
            text.setValue("Cards spawn here")
            text.setColorTint("White")

            local size = 2.5
            text.setScale(v(size, size, size))
        end
    }
    spawnObject(spawnParams)
end

function createTabletSnapPoint(plate)
    local parentSize = plate.getBoundsNormalized().size
    local pos = util.relativeLocalToWorldPosition2D(plate, parentSize, -0.85, 0.4)
    pos = plate.positionToLocal(pos)
    plate.setSnapPoints({
        {
            position = pos
        }
    })
end

function createPlate(table)
    spawnParams = {
        type = "Custom_Model",
        position = table.getPosition() + v(0, 0.1, 0),
        rotation = table.getRotation(),
        scale = plateScale,
        sound = false,
        snap_to_grid = false,
    }
    local plate = spawnObject(spawnParams)
    plate.setCustomObject({
        mesh = "http://cloud-3.steamusercontent.com/ugc/783002817662121296/661D8FFE6699A4D022FB10D87979B2028D8D1806/",
        diffuse = "http://cloud-3.steamusercontent.com/ugc/783002817662118580/EEF2FF28224A83EB29EC7D5B3CA728782F1554FC/",
        collider = "http://cloud-3.steamusercontent.com/ugc/783002817662121296/661D8FFE6699A4D022FB10D87979B2028D8D1806/",
        type = 4,
        material = 1,
        specular_intensity = 0,
        specular_sharpness = 3,

    })

    local f = function()
        plate.locked = true
        createHiddenZones(plate)
        createText(plate)
        createTabletSnapPoint(plate)
    end

    -- Wait insteal of callback because the plate needs to fall down on the table
    Wait.time(f, 1)
end

function createTable(pos, rotation)
    spawnParams = {
        type = "Custom_Assetbundle",
        position = pos,
        rotation = rotation,
        scale = tableScale,
        sound = false,
        snap_to_grid = true,
        callback_function = |table| createPlate(table)
    }
    local table = spawnObject(spawnParams)
    table.locked = true
    table.setCustomObject({
        assetbundle = "http://cloud-3.steamusercontent.com/ugc/1011563587901306704/1ED59A7E6C52632AF229D6017BB616F051EAE049/",
        type = 4,
        material = 1,
    })
end

function module.create(pos, rotation)
    createTable(pos, rotation)
end

return module
