-- import:
--local c = require("TTS-YGO-sealed-draft/dev/draft-table/DraftTableCreator")

local cardGridJson = require("TTS-YGO-sealed-draft/dev/draft-table/CardGrid")

local module = {}

local v = Vector
local pos = v(60, 2, 50)
local rotation = v(0, 90, 0)

local tableScale = v(3.50, 1.00, 2.00)
local plateScale = v(0.85, 0.20, 0.47)

function createCardGrid(pos, rotation)
    spawnParams = {
        json              = cardGridJson,
        position          = pos,
        rotation          = rotation,
        scale             = {x=9, y=2, z=9},
        sound             = false,
        snap_to_grid      = true,
        callback_function = function(obj) end
    }
    spawnObjectJSON(spawnParams)
end

function createCardGrids()
    local firstLeftPosition = pos + v(-23, 1, 102)
    local firstRightPosition = pos + v(23, 1, 102)
    local leftRotation = rotation + v(0, 180, 0)
    local rightRoration = rotation

    local p = firstLeftPosition
    for i=1,4 do
        createCardGrid(p, leftRotation)
        p = p + v(0, 0, -50)
    end

    p = firstRightPosition
    for i=1,4 do
        createCardGrid(p, rightRoration)
        p = p + v(0, 0, -50)
    end
end

function createHiddenZone(pos, color)
    spawnParams = {
        type = "FogOfWarTrigger",
        position = pos,
        rotation = rotation,
        scale = v(40, 15, 60),
        sound = false,
        snap_to_grid = false,
        callback_function = |zone| zone.setValue(color)
    }
    spawnObject(spawnParams)
end

function createHiddenZones()
    local color = {"Green", "Teal", "Blue", "Purple", "White", "Red", "Orange", "Yellow"}
    local first = pos + v(-38, 7, 102.5)
    local p = first

    for i=1,4 do
        createHiddenZone(p, color[i])
        p = p + v(0, 0, -50)
    end

    p = first + v(38*2, 0, 0)
    for i=5,8 do
        createHiddenZone(p, color[i])
        p = p + v(0, 0, -50)
    end

end

function createText()
    spawnParams = {
        type = "3DText",
        position = pos + v(15, 5, -100),
        rotation = v(90,0,0),
        scale = plateScale,
        sound = false,
        snap_to_grid = false,
        callback_function = function(text)
            text.setValue("Cards spawn here")
            text.setColorTint("White")
        end
    }
    spawnObject(spawnParams)
end

function createPlate()
    spawnParams = {
        type = "Custom_Model",
        position = pos + v(0, 0.1, 0),
        rotation = rotation,
        scale = plateScale,
        sound = false,
        snap_to_grid = false,
        callback_function = function(obj) end
    }
    local plate = spawnObject(spawnParams)
    plate.setCustomObject({
        mesh = "http://cloud-3.steamusercontent.com/ugc/783002817662121296/661D8FFE6699A4D022FB10D87979B2028D8D1806/",
        diffuse = "http://cloud-3.steamusercontent.com/ugc/783002817662118580/EEF2FF28224A83EB29EC7D5B3CA728782F1554FC/",
        collider = "http://cloud-3.steamusercontent.com/ugc/783002817662121296/661D8FFE6699A4D022FB10D87979B2028D8D1806/",
        type = 4,
        material = 1,
        specular_intensity = 0,
        specular_sharpness = 3,

    })

    local f = function()
        plate.locked = true
        createCardGrids()
        createHiddenZones()
        createText()
    end

    Wait.time(f, 1)
end

function createTable()
    spawnParams = {
        type = "Custom_Assetbundle",
        position = pos,
        rotation = rotation,
        scale = tableScale,
        sound = false,
        snap_to_grid = true,
        callback_function = function(obj) createPlate() end
    }
    local table = spawnObject(spawnParams)
    table.locked = true
    table.setCustomObject({
        assetbundle = "http://cloud-3.steamusercontent.com/ugc/1011563587901306704/1ED59A7E6C52632AF229D6017BB616F051EAE049/",
        type = 4,
        material = 1,
    })
end

function module.create()
    createTable()
end

return module
