
local draftTable = require("TTS-YGO/dev/room-creation/draft-table/DraftTableCreator")
local playTable = require("TTS-YGO/dev/room-creation/play-table/PlayTableCreator")
local util = require("TTS-YGO/dev/room-creation/Util")

local POS = Vector(13.5, 2, 0)
local ROTATION = Vector(0, 90, 0)

local module = {}

function module.create()
    local pos = POS + Vector(0, 0, -100)
    local rotation = ROTATION
    draftTable.create(pos, rotation)

    pos = pos + Vector(150, 0, -96)
    rotation = rotation + Vector(0, 180, 0)
    local colors = util.getPlayerColors()

    for i=1,4 do
        local temp = pos:copy()
        Wait.time(||playTable.create(temp, rotation, colors[i], colors[i+4]), 3)
        pos = pos + Vector(0, 0, 64)
    end

end

return module
