local script = {}

function script.createLuaScript(folder, file, spawn, name)
    return string.format([=====[
local logic = require("TTS-YGO-sealed-draft/src/pack-logic/%s/%s")

local packGenerator = logic.createPackGenerator()

function onClick()
    packGenerator.generateBoosterBox(packGenerator, %s)
end

function onload()
    self.createButton({
        click_function = "onClick",
        function_owner = self,
        width=1150,
        height=1900,
        color= {r=1, g=0, b=0},
        tooltip=[[%s]]
    })
end
]=====], folder, file, spawn, name)
end

return script
