local script = {}

function script.createLuaScript(folder, file, spawn, name)
    return string.format([=====[
%s <TTS-YGO-sealed-draft/src/pack-logic/%s/%s>

local packGenerator = PackGenerator:new()

function onClick()
    packGenerator:generateBoosterBox(%s)
end

function onload()
    self.createButton({
        click_function = "onClick",
        function_owner = self,
        width=1150,
        height=1900,
        color= {r=1, g=0, b=0},
        tooltip="%s"
    })
end
]=====], "#include", folder, file, spawn, name)
end

return script
