local script = {}

local SPAWN = "{x = 0, y = 5, z = 30}"

function script.createLuaScript(folder, file)
    return string.format([=====[
%s <TTS-YGO-sealed-draft/src/pack-logic/%s/%s>

local packGenerator = PackGenerator:new()

function onClick()
    packGenerator:generateBoosterBox(%s)
end

function onload()
    self.createButton({
        click_function = "onClick",
        function_owner = self,
        width=1150,
        height=1900,
        color= {r=1, g=0, b=0}
    })
end
]=====], "#include", folder, file, SPAWN)
end

return script
