local ParentGenerator = require("TTS-YGO/src/pack-spawning/pack-logic/core-sets/_CoreSetLogicA")

local PackGenerator = ParentGenerator:new()

function PackGenerator:new()
    local o = ParentGenerator:new()
    setmetatable(o, self)
    self.__index = self

    o.setName = "Invasion of Chaos"
    o.setCodePrefix = "IOC-EN"
    o.setNameUrl = "Invasion of Chaos"
    o.releaseDate = "2004-03-01"
    o.packTextures = "https://i.imgur.com/KjH2fqs.png"
    o.boxTexture = "https://i.imgur.com/cvyXhQf.png"

    return o
end

return PackGenerator
