local module = {}

function module.distinct(input)
    local output = {}
    local encountered = {}

    for _,v in ipairs(input) do
        if not encountered[v] then
            table.insert(output, v)
            encountered[v] = true
        end
    end

    return output
end

function module.toSet(table)
    local set = {}
    for _, v in ipairs(table) do
        set[v] = true
    end
    return set
end

return module
